# If true, player will be able to be revived with the /civ pardonall command
# If false, player will be banned forever.
temp-death: false

# World used by the plugin, leave blank to use world
world :

# Will tp players to their island if true.
session-started : false

# List all areas.
# Correct syntax :
# area-name :
#   x1 :
#   z1 :
#   x2 :
#   z2 :
areas :

# To remember who has already been tp-ed to their area.
teleported-players :