# If true, player will be able to be revived with the /civ pardonall command
# If false, player will be banned forever.
temp-death: false

# World used by the plugin, leave blank to use world
world :

# List all areas.
# Correct syntax :
# area-name :
#   x1 :
#   z1 :
#   x2 :
#   z2 :
areas :