name: OSE_Civilisation
version: 0.1
main: fr.tbrpower.ose_civilisation.OSE_Civilisation
api-version: 1.21
author: TbrPower
description: Brr Brr le patapim du joueur

commands:
  civ :
    description : Main plugin command
    usage : /civ <action>
    permission : civcde.admin

permissions:
  civde.bypass:
    description: ignores death check
    default: false