name: OSE_Civilisation
version: 0.2
main: fr.tbrpower.ose_civilisation.OSE_Civilisation
api-version: 1.21
author: TbrPower
description: "Utility plugin for for easier management of Civilization events. Made by TbrPower for ONLY $U$ Events "


commands:
  civ :
    description : Main plugin command
    usage : /civ <action>
    permission : oseciv.admin

permissions:
  oseciv.bypass:
    description: ignores death check and kick
    default: op

  oseciv.area. :
    description: add area name to tp player, use syntax "oseciv.area.<name>"
    default: false

    oseciv.admin :
      description : Allows every command in the plugin, only give to trusted players.
      default : false